import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { buildCustomHostState, CustomAppHostDemo } from '../../examples/custom-app-host/src/App'

const exampleRoot = join(process.cwd(), 'examples', 'custom-app-host')

describe('standalone custom app host template', () => {
  it('uses only public nirs4all and nirs4all-ui imports', () => {
    const source = readFileSync(join(exampleRoot, 'src', 'App.tsx'), 'utf8')
    const readme = readFileSync(join(exampleRoot, 'README.md'), 'utf8')

    expect(source).toContain("from 'nirs4all'")
    expect(source).toContain("from 'nirs4all-ui/components'")
    expect(source).toContain("from 'nirs4all-ui/conformal'")
    expect(source).toContain("from 'nirs4all-ui/dataset'")
    expect(source).toContain("from 'nirs4all-ui/keywordRegistry'")
    expect(source).toContain("from 'nirs4all-ui/robustness'")
    expect(source).toContain("from 'nirs4all-ui/runtime'")
    expect(source).toContain("from 'nirs4all-ui/tuning'")
    expect(source).not.toContain("from '@/")
    expect(source).not.toContain("from '../../src/")
    expect(readme).toContain('conformal.calibrated_result')
    expect(readme).toContain('robustness.summary')
    expect(readme).toContain('tuning.summary')
    expect(readme).toContain('tuning.ordered_search_space')
    expect(readme).toContain('keyword.registry')
    expect(readme).toContain('required_registry_entries')
    expect(readme).toContain('run.tuning.space')
    expect(readme).toContain('robustness.X')
    expect(readme).toContain('robustness.predictor')
    expect(readme).toContain('robustness.predictor_bundle')
    expect(readme).toContain('metadata contracts')
    expect(readme).toContain('does not compute conformal quantiles')
  })

  it('exposes reusable core and UI surfaces without app internals', () => {
    const state = buildCustomHostState()
    const source = readFileSync(join(exampleRoot, 'src', 'App.tsx'), 'utf8')

    expect(state.predictSurface).toBe('javascript_wasm')
    expect(state.controllerCount).toBeGreaterThanOrEqual(4)
    expect(state.artifactContractCount).toBe(5)
    expect(state.artifactContractIds).toBe(
      'conformal.calibrated_result, robustness.summary, tuning.summary, tuning.ordered_search_space, keyword.registry',
    )
    expect(state.conformalCoverageLabel).toBe('80%, 90%')
    expect(state.conformalIntervalCount).toBe(2)
    expect(state.conformalStatus).toBe('active')
    expect(state.conformalTuningCalibrationLabel).toBe('tuning winner; score_data ranked trials only')
    expect(state.datasetTitle).toBe('Custom host demo dataset')
    expect(state.engineLabel).toBe('Nirs4all Core Wasm')
    expect(state.keywordEngineOptions).toBe('null, legacy, dag-ml, dual')
    expect(state.keywordRequiredRegistryEntryCount).toBe(14)
    expect(state.keywordRequiredRegistryEntries).toContain('run.tuning.space')
    expect(state.keywordRequiredRegistryEntries).toContain('run.tuning.force_params')
    expect(state.keywordRequiredRegistryEntries).toContain('predict.coverage')
    expect(state.keywordRequiredRegistryEntries).toContain('robustness.X')
    expect(state.keywordRequiredRegistryEntries).toContain('robustness.predictor')
    expect(state.keywordRequiredRegistryEntries).toContain('robustness.predictor_bundle')
    expect(state.keywordRegistrySectionCount).toBe(1)
    expect(state.runtimeLabel).toBe('executed by dag-ml')
    expect(state.robustnessGuaranteeCoverageLabel).toBe('80%')
    expect(state.robustnessGuaranteeStatus).toBe('invalidated')
    expect(state.robustnessReplaySource).toBe('predictor_bundle via nirs4all.predict')
    expect(state.robustnessStatus).toBe('ok')
    expect(state.tuningBestValue).toBe('0.031')
    expect(state.tuningCompleteTrials).toBe(2)
    expect(state.tuningPruner).toBe('median')
    expect(state.tuningSampler).toBe('grid')
    expect(state.tuningSeed).toBe('42')
    expect(state.tuningSpaceForcedParameters).toBe(2)
    expect(state.tuningSpaceParameters).toBe(3)
    expect(state.tuningSpaceSchema).toBe('https://nirs4all.org/schemas/tuning-ordered-search-space/v1')
    expect(state.tuningTrialCount).toBe(3)
    expect(CustomAppHostDemo).toBeTypeOf('function')
    expect(source).toContain('aria-label="nirs4all custom app host"')
    expect(source).toContain('DatasetPreviewCard')
    expect(source).toContain('RuntimeEngineBadge')
    expect(source).toContain('MetricValueBadge')
    expect(source).toContain('createRobustnessSummaryCards')
    expect(source).toContain('createRobustnessGuaranteeView')
    expect(source).toContain('getRobustnessSpectralReplay')
    expect(source).toContain('parseRobustnessSummaryArtifact')
    expect(source).toContain('createConformalGuaranteeViewForArtifact')
    expect(source).toContain('createConformalIntervalSummaryRows')
    expect(source).toContain('createKeywordRegistryFormSections')
    expect(source).toContain('Runtime predict surface')
    expect(source).toContain('Robustness guarantee status')
    expect(source).toContain('Robustness guarantee coverage')
    expect(source).toContain('Robustness spectral replay')
    expect(source).toContain('Native artifact contracts')
    expect(source).toContain('Native artifact contract ids')
    expect(source).toContain('Conformal guarantee status')
    expect(source).toContain('Conformal interval coverages')
    expect(source).toContain('Keyword registry sections')
    expect(source).toContain('Required registry entries')
    expect(source).toContain('Required registry entry ids')
    expect(source).toContain('Execution backend options')
    expect(source).toContain('Tuning best value')
    expect(source).toContain('Tuning complete trials')
    expect(source).toContain('Tuning sampler')
    expect(source).toContain('Tuning pruner')
    expect(source).toContain('Tuning seed')
    expect(source).toContain('Tuning search-space schema')
    expect(source).toContain('Tuning search-space parameters')
    expect(source).toContain('Tuning forced parameters')
    expect(source).toContain('Tuning trial rows')
    expect(source).toContain('parseOrderedTuningSearchSpaceArtifact')
    expect(source).toContain('createTuningSearchSpacePreview')
  })
})
