/* tslint:disable */
/* eslint-disable */

export function _start(): void;

/**
 * Feature flags the WASM build was compiled with. Useful for runtime checks
 * from JS ("does this WASM bundle have HDF5 support?").
 *
 * The default browser build enables `fmt-hdf5`, `fmt-matlab`, and
 * `fmt-parquet`, including snappy, uncompressed, and zstd Parquet pages.
 */
export function features(): any;

/**
 * Decode a file by name + bytes. Returns the spectral records as a JS array
 * matching the JSON shape produced by `nirs4all-formats read-json`.
 *
 * Sidecar formats (ENVI Standard, AVIRIS LAN, FGI HDF5+XML, ...) return an
 * `UnsupportedSidecar` error here; use `openWithSidecars` instead.
 * Single-file HDF5 / NetCDF payloads decode directly through this entry
 * point now that `fmt-hdf5` is on.
 */
export function openBytes(filename: string, bytes: Uint8Array): any;

/**
 * Decode a file by name + bytes plus a map of sidecar names → byte
 * payloads. Keys are relative path names (e.g. `"foo.hdr"` next to the
 * primary file). For the WASM build this powers ENVI Standard, ENVI SLI,
 * AVIRIS/ERDAS LAN and the HDF5-backed sidecar formats (FGI XML+HDF5,
 * NetCDF MFRSR with its QC YAML) now that `fmt-hdf5` is on.
 */
export function openWithSidecars(filename: string, bytes: Uint8Array, sidecars: any): any;

/**
 * Probe a file by name + bytes. Returns the ordered candidate readers.
 *
 * The file name is required because several sniffers disambiguate by
 * extension (`.lan`, `.spc`, `.hdr`, ...). The first 8 KB of `bytes` is
 * inspected; pass the entire buffer or just the head — the implementation is
 * the same.
 */
export function probeBytes(filename: string, bytes: Uint8Array): any;

/**
 * Readers compiled into this WASM bundle.
 *
 * This is intentionally generated by the Rust registry rather than duplicated
 * in JavaScript, so browser UIs can show the real format coverage of the
 * loaded bundle.
 */
export function readerCatalog(): any;

export function recommended_chunk_size_mb(): number;

/**
 * Return the sidecars declared by the matching format reader for this named
 * payload. The rules live inside each format module; this binding only
 * serializes them for browser UIs.
 */
export function sidecarRequirements(filename: string, bytes: Uint8Array): any;

/**
 * Crate version exposed to JS.
 */
export function version(): string;

export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;

export interface InitOutput {
    readonly memory: WebAssembly.Memory;
    readonly _start: () => void;
    readonly features: () => [number, number, number];
    readonly openBytes: (a: number, b: number, c: number, d: number) => [number, number, number];
    readonly openWithSidecars: (a: number, b: number, c: number, d: number, e: any) => [number, number, number];
    readonly probeBytes: (a: number, b: number, c: number, d: number) => [number, number, number];
    readonly readerCatalog: () => [number, number, number];
    readonly sidecarRequirements: (a: number, b: number, c: number, d: number) => [number, number, number];
    readonly version: () => [number, number];
    readonly rust_zstd_wasm_shim_calloc: (a: number, b: number) => number;
    readonly rust_zstd_wasm_shim_free: (a: number) => void;
    readonly rust_zstd_wasm_shim_malloc: (a: number) => number;
    readonly rust_zstd_wasm_shim_memcmp: (a: number, b: number, c: number) => number;
    readonly rust_zstd_wasm_shim_memcpy: (a: number, b: number, c: number) => number;
    readonly rust_zstd_wasm_shim_memmove: (a: number, b: number, c: number) => number;
    readonly rust_zstd_wasm_shim_memset: (a: number, b: number, c: number) => number;
    readonly rust_zstd_wasm_shim_qsort: (a: number, b: number, c: number, d: number) => void;
    readonly recommended_chunk_size_mb: () => number;
    readonly __wbindgen_malloc: (a: number, b: number) => number;
    readonly __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
    readonly __wbindgen_exn_store: (a: number) => void;
    readonly __externref_table_alloc: () => number;
    readonly __wbindgen_externrefs: WebAssembly.Table;
    readonly __externref_table_dealloc: (a: number) => void;
    readonly __wbindgen_free: (a: number, b: number, c: number) => void;
    readonly __wbindgen_start: () => void;
}

export type SyncInitInput = BufferSource | WebAssembly.Module;

/**
 * Instantiates the given `module`, which can either be bytes or
 * a precompiled `WebAssembly.Module`.
 *
 * @param {{ module: SyncInitInput }} module - Passing `SyncInitInput` directly is deprecated.
 *
 * @returns {InitOutput}
 */
export function initSync(module: { module: SyncInitInput } | SyncInitInput): InitOutput;

/**
 * If `module_or_path` is {RequestInfo} or {URL}, makes a request and
 * for everything else, calls `WebAssembly.instantiate` directly.
 *
 * @param {{ module_or_path: InitInput | Promise<InitInput> }} module_or_path - Passing `InitInput` directly is deprecated.
 *
 * @returns {Promise<InitOutput>}
 */
export default function __wbg_init (module_or_path?: { module_or_path: InitInput | Promise<InitInput> } | InitInput | Promise<InitInput>): Promise<InitOutput>;
